---

- name: Arista-Ansible Exercise2
  hosts: arista

  tasks:
    - name: Set interface description.
      eos_interface: name=Ethernet6 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Set interface to access mode on VLAN 309.
      eos_switchport: name=Ethernet6 mode=access access_vlan=309
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https


